### ISSUE TITLE
would you accept a PR for amazon alexa cert validation?

### ISSUE THREAD

**Issue by mreinstein** [mattotodd/node-red-contrib-alexa#2]
getting an alexa skill certified and published requires validating the requests are actually coming from Amazon. I wrote an npm module that handles these low-level details:

https://github.com/mreinstein/alexa-verifier

I have a client that is using `node-red-contrib-alexa` and is asking for this capability. Would you be open to a pull request that incorporates this?

**Comment by mattotodd** [comment]
Sorry i took so long to respond @mreinstein . Yes, no problem with the pull request
