### ISSUE TITLE
why is alexa-app embeded in vendor/ rather than installing as an npm module?

### ISSUE THREAD

**Issue by mreinstein** [mattotodd/node-red-contrib-alexa#3]
https://github.com/mattotodd/node-red-contrib-alexa/blob/master/vendor/alexa-app.js looks identical to the `alexa-app` module from npm.

Were there slight changes made to the local copy of this module? Could we instead just pull that module in as a normal dependency? would reduce a lot of duplication and leverage node/npm's module system more elegantly.

**Comment by mattotodd** [comment]
Yes, i had to make a slight change to the alex-app to support node-red,  and I have a pull request open on that repo with the changes. https://github.com/matt-kruse/alexa-app/pull/70

If/when that gets pulled in,  it will become a dependency
